batch_size: 128
data_dir: /content/drive/MyDrive/dl_lecture_competition_pub/data
device: cuda:0
dropout: 0.1
epochs: 50
hid_dim: 512
lr: 0.001
model_path: null
num_workers: 4
seed: 1234
transformer_heads: 16
transformer_layers: 8
use_wandb: false
weight_decay: 0.01
